import type { Song } from '../songService/schema';

export type AppStore = {
  songs: Song[];
  currentSong: Song | null;
  currentPlaying: boolean;
  favoriteSongs: Song[];
  query: string;
  offset: number;
  limit: number;
  page: number;
  results: number;
  autoplay: boolean;
  repeat: boolean;
  setAutoplay: (value: boolean) => void;
  setRepeat: (value: boolean) => void;
  getAudio: () => HTMLAudioElement;
  play: () => void;
  pause: () => void;
  next: () => void;
  previous: () => void;
  setCurrent: (song: Song | null) => void;
  setCurrentPlaying: (isPlaying: boolean) => void;
  setQuery: (query: string) => void;
  setPage: (page: number) => void;
  getSongs: (query: string) => void;
  addFavoriteSong: (song: Song) => void;
  removeFavoriteSong: (id: string) => void;
  setSongs: (songs: Song[]) => void;
  removeSong: (id: string) => void;
  removeAllSongs: () => void;
};
