export const autocompleteSuggestions: string[] = [
  'Love Song',
  'Summer Vibes',
  'Chill Beats',
  'Rock Anthem',
  'Jazz Night',
  'Electronic Pulse',
  'Classical Piano',
  'Hip Hop Flow',
  'Indie Dreams',
  'Pop Star',
  'R&B Grooves',
  'Acoustic Sessions',
  'Latin Heat',
  'Reggae Wave',
  'Workout Mix',
  'Morning Motivation',
  'Late Night Drive',
  'Lofi Study',
  'Throwback Hits',
  'Dance Party',
  'Soul Classics',
  'Country Roads',
  'Heavy Metal',
  'Punk Spirit',
  'Folk Tales',
  'Blues Mood',
  'Instrumental Peace',
  'Trance Energy',
  'Dubstep Drop',
  'K-Pop Fever',
  'EDM Rush',
  'Chillwave',
  '80s Flashback',
  '90s R&B',
  'Disco Inferno',
  'Techno Night',
  'World Fusion',
  'Arabic Rhythms',
  'Bollywood Beats',
  'Afro Pop',
  'Gospel Glory',
  'Kids Songs',
  'Happy Tunes',
  'Sad Songs',
  'Romantic Ballads',
  'Piano Chill',
  'Guitar Solo',
  'Drum & Bass',
  'Ambient Flow',
  'Meditation Music',
  'Nature Sounds',
  'Festival Anthems',
  'Rap Battles',
  'Cover Hits',
  'Live Sessions',
  'DJ Sets',
  'Mixtape Madness',
  'Club Bangers',
  'Sing-Along',
  'Road Trip',
  'Coffeehouse',
  'Study Vibes',
  'Sleep Aid',
  'Soundtracks',
  'Game Music',
  'Anime Themes',
  'TV Show Hits',
  'Movie Scores',
  'Holiday Cheer',
  'Christmas Tunes',
  'New Year Party',
  'Halloween Sounds',
  'Valentine Vibes',
  'Rainy Day',
  'Sunny Afternoon',
  'Golden Oldies',
  'Indie Pop',
  'Future Bass',
  'Tropical House',
  'Breakup Songs',
  'Makeup Songs',
  'Feel Good',
  'Melancholy',
  'Drive Fast',
  'Slow Dance',
  'Background Music',
  'Cover Classics',
  'Street Rap',
  'Love Ballads',
  'Party Starters',
  'Garage Rock',
  'Synthwave',
  'Dream Pop',
  'Trap Beats',
  'Rap Classics',
  'Neo Soul',
  'Sad Rap',
  'Hype Music',
  'Chillhop',
  'Relaxation',
  'Yoga Flow',
  'Morning Chill',
  'Night Jazz',
  'Open Mic',
];
